### ISSUE TITLE
Syntax Error Catching in invalid char after number/name

### ISSUE THREAD

**Issue by MoseslGit** [anirudhbhalekar/GF2P2#1]
In the current scanner module, we just advance a character if the character is invalid. This might cause a problem where we have an input like "inputs=2E;", where the E is ignored. 

Should we throw a syntax error in this case? It currently won't get caught by the parser because the scanner will automatically skip over to the semicolon (as after calling get_name(), there are no more if statements for a character).

**Comment by MoseslGit** [comment]
As a side note, I've also added an extra syntax error for when we expect a number but don't get one, error code 11.

**Comment by anirudhbhalekar** [comment]
If we just do an advance, the symbol type is already set to none by default. In the parser perhaps we can add a statement that raises errors when there is a none type symbol. In the example you stated the following would be returned by the scanner: 

param type - input
equal type - = 
number - 2 
name - E 

in the parser then - we expect a semi colon - if we instead receive a name - we throw an error

if the line was instead - "inputs = 2$" where the dollar sign is a none type symbol - the parser will again catch it because it expects a semi colon type symbol not the none type. 

So essentially these errors are automatically dealt with by setting symbol type and id to None by default

**Comment by MoseslGit** [comment]
Sounds good, in that case I'm implementing both letter/digit as EXPECTED_NAME or EXPECTED_NUMBER to catch any exceptions, which will work no matter the type of symbol returned. For the above error, we will throw a "missing semicolon" error instead.

Example of EXPECTED_NUMBER use:
        if self.symbol.type == self.scanner.NUMBER:
            self.symbol = self.scanner.get_symbol()
        else:
            self.error(self.EXPECTED_NUMBER)
