### ISSUE TITLE
Scanner tests

### ISSUE THREAD

**Issue by MoseslGit** [anirudhbhalekar/GF2P2#3]
Hi @anirudhbhalekar ,

I've found that scanner symbols seem to be returning None, at least in the ways we are currently calling them. Could you please double check the implementation logic according to the unit tests currently implemented? We can also discuss later.

**Comment by MoseslGit** [comment]
Current changes made to scanner:
- Added "AS" as a keyword

Requests:
- How does symbol.id of number work? Is it that we need to check that type is a number, and if so we know it is a string (else it is an integer?)
- I think I might be misunderstanding how we are returning symbols: current unit tests aren't going through and not too sure why.

**Comment by anirudhbhalekar** [comment]
I'll have a look at the unit tests. Symbol id refers to the symbol class. So scanner will return a symbol type object everytime get_symbol() is called. So lets say we assign this to a variable 'next_sym' we check the id just by checking next_sym.id

I'll make edits to the tests- the scanner class does not have a .symbol_id itself because thats just the property of the symbol class. 

For numbers i've made the id a string version of it for the time being. So the type is NUMBER and to get the value we just convert the id into an int

**Comment by anirudhbhalekar** [comment]
I've seen some of your tests and I get the confusion. Right now the symbol ids for Keywords are not strings - but they are integers ranged 0-11 (at the moment). I can change it to strings for ease of use - I imagine the parser is depending on that
