### ISSUE TITLE
Parse infinite loop

### ISSUE THREAD

**Issue by anirudhbhalekar** [anirudhbhalekar/GF2P2#6]
I've been trying to debug test_parse - I think there is an infinite while loop hidden somewhere in parse thats causing the issue. The main issue is in parsing some of the error_def_files. Detailing some of the code below - the problematic test in test_parse is the following chunk: 

`
def test_error_definition_files(error_file_path): 
    ''' Tests the definition files with errors -- these should all return False as they don't contain errors.
    Furthermore the number of errors should be equal to the actual (hardcoded) number of errors in each file'''

    names = Names()
    scanner = Scanner(error_file_path, names)

    devices = Devices(names)
    network = Network(names, devices)
    monitors = Monitors(names, devices, network)
    parser = Parser(names, devices, network, monitors, scanner) 
    
    bool_parse = parser.parse_network()
    # Have to ensure the error codes are consistent as well

    assert not bool_parse`

Somewhere in the error_definition_files folders theres a file thats causing an inf loop. This is probably an error catching failure - we might have to comb through and find where it expects KEYWORDS or punctuation and how it handles NAMES or anything else

**Comment by MoseslGit** [comment]
There are 4 while loops in parse, and three of them terminate when symbol is no longer a COMMA, which should all terminate properly as they will continuously call get_symbol, which eventually returns a EOF, or failing that, a None.

I'm guessing the only possible option is for it to be cause by the following while loop, which only terminates at a stopping symbol or EOF, suggesting that we may not be passing the EOF correctly in one of the files.

I added a unit test to scanner to see if the EOF symbol is passed and it isn't.

Turns out that for all interim1 error files the comments aren't properly terminated, so scanner goes into an infinite loop reading the next character. Could you please fix this in scanner?

e.g. line 4 here
DEFINE
    G1 AS NAND WITH inputs=2, 
    G2 AS NAND WITH inputs=2,
    SW1 AS SWITCH WITH initial=0; **% ERROR HERE (WRONG PUNCTUATION)**
    SW2 AS SWITCH WITH initial=0;	

CONNECT 
    G1.I1 = SW1,
    G1.I2 = SW2;    

% For readability, we recommend indenting all further connect
statements to the same level as the initial statement %

MONITOR 
    G1,
    G2;

END;

**Comment by MoseslGit** [comment]
Resolved with EOF passed from scanner.
